# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import kalachakra_pb2 as kalachakra__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in kalachakra_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CosmicWeatherStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
                '/kalachakra.CosmicWeather/Health',
                request_serializer=kalachakra__pb2.HealthRequest.SerializeToString,
                response_deserializer=kalachakra__pb2.HealthReply.FromString,
                _registered_method=True)
        self.Inspect = channel.unary_unary(
                '/kalachakra.CosmicWeather/Inspect',
                request_serializer=kalachakra__pb2.InspectRequest.SerializeToString,
                response_deserializer=kalachakra__pb2.InspectReply.FromString,
                _registered_method=True)
        self.Telemetry = channel.unary_unary(
                '/kalachakra.CosmicWeather/Telemetry',
                request_serializer=kalachakra__pb2.TelemetryRequest.SerializeToString,
                response_deserializer=kalachakra__pb2.TelemetryReply.FromString,
                _registered_method=True)


class CosmicWeatherServicer:
    """Missing associated documentation comment in .proto file."""

    def Health(self, request, context):
        """Liveness + which temporal-mipmap tiers are populated.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Inspect(self, request, context):
        """Viewport query -> tier-routed rows, band gains, mean latent, clusters.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Telemetry(self, request, context):
        """Raw numerical constituents at one coordinate + time (Sidebar Inspector).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CosmicWeatherServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=kalachakra__pb2.HealthRequest.FromString,
                    response_serializer=kalachakra__pb2.HealthReply.SerializeToString,
            ),
            'Inspect': grpc.unary_unary_rpc_method_handler(
                    servicer.Inspect,
                    request_deserializer=kalachakra__pb2.InspectRequest.FromString,
                    response_serializer=kalachakra__pb2.InspectReply.SerializeToString,
            ),
            'Telemetry': grpc.unary_unary_rpc_method_handler(
                    servicer.Telemetry,
                    request_deserializer=kalachakra__pb2.TelemetryRequest.FromString,
                    response_serializer=kalachakra__pb2.TelemetryReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kalachakra.CosmicWeather', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kalachakra.CosmicWeather', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CosmicWeather:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kalachakra.CosmicWeather/Health',
            kalachakra__pb2.HealthRequest.SerializeToString,
            kalachakra__pb2.HealthReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Inspect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kalachakra.CosmicWeather/Inspect',
            kalachakra__pb2.InspectRequest.SerializeToString,
            kalachakra__pb2.InspectReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Telemetry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kalachakra.CosmicWeather/Telemetry',
            kalachakra__pb2.TelemetryRequest.SerializeToString,
            kalachakra__pb2.TelemetryReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
